### PR TITLE
Helm chart rework

### PR DESCRIPTION
**Pull request by HaveFun83**
Did some refactoring on the helm chart to match the helm best practices
* spit deployment files into "single objects"
* join values from rbac and serviceAccount
* removed namespace creation. As helm v2 will create one during install and on helm v3 the namespace must already created before install.
* removed common.configMapName . This will be generated from the release-name
* removed daemonset.name. This will be generated from the helm release-name
* removed daemonset.serviceAccount  This will be generated from the helm release-name
* changed metadata.labels 
* rework the Prometheus servicemonitor creation

Please have a look. Feedback is welcome
Thanks

### CODE REVIEW

**Comment by HaveFun83** [comment]
cla signed

**Comment by HaveFun83** [comment]
I signed it

**Comment by cofyc** [comment]
hi, Thanks for working this!
By the way, can you run `hack/update-generated.sh` to generate helm output examples under `helm/generated_examples`?

**Comment by cofyc** [comment]
it seems that the comments in your path have more than one author information. maybe one of them does not pass CLA check?

**Comment by HaveFun83** [comment]
> hi, Thanks for working this!
> By the way, can you run `hack/update-generated.sh` to generate helm output examples under `helm/generated_examples`?

Done via https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/pull/171/commits/8786ba0922e6bd46633b3aea7c81164e1afdcf14

I also removed the obsolete /examples/baremetal-namespace.yaml as the namespace will be set during helm install.

**Comment by HaveFun83** [comment]
Maybe someone can tell me what is wrong on the failed job.

**Comment by HaveFun83** [comment]
Maybe the Helm-Chart version should be raised to v2.4.0 or v3.0.0  to reflect the changes made.
Any thoughts?

**Comment by cofyc** [comment]
yes, the major version must be incremented because the change is not backward compatible. Can you also tell users the new chart is not backward compatibility and how to migrate to the new helm chart in [CHANGELOG HEAD section](https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/blob/master/CHANGELOG.md#head)?  

by the way, is the chart is helm 3 compatible after this change?

**Comment by HaveFun83** [comment]
> yes, the major version must be incremented because the change is not backward compatible. Can you also tell users the new chart is not backward compatibility and how to migrate to the new helm chart in [CHANGELOG HEAD section](https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/blob/master/CHANGELOG.md#head)?
Ok need some time to do it later this week.

> by the way, is the chart is helm 3 compatible after this change?
Yes currently deployed with helm 3

By the way  the helm test job should be improved to support helm 2 and 3 and some other stuff. Is this something you already discuss internally?

**Comment by cofyc** [comment]
> Ok need some time to do it later this week.

thanks! no hurry.

> By the way the helm test job should be improved to support helm 2 and 3 and some other stuff. Is this something you already discuss internally?

no, we hope the chart is compatible both with helm 2 and helm 3, but we don't have helm tests for this. I'm not sure what's the best practice to test the helm chart. Currently, we have only a basic test to verify the output of `helm template`. maybe we can test the output of `helm 3` too.

**Comment by cofyc** [comment]
the e2e failure can be ignored, the test-infra has a problem right now: https://github.com/kubernetes/test-infra/issues/16202)

**Comment by msau42** [comment]
@cofyc since this requires a new major version, do we want to release a new minor version first before this PR?

Is there an upgrade story for this, or will users have to completely tear down the old provisioner, and then create a new one?

**Comment by HaveFun83** [comment]
@cofyc i added some docu and a changelog placeholder with the last two commits. Will be great if you can have a look into it and give me some feedback.
Will be looking into helm 3 generated / verify script now.

**Comment by HaveFun83** [comment]
/assign @cofyc
Please have a look. Thanks in advanced

**Comment by cofyc** [comment]
Great work! It's a big PR, I need some time to review and test locally. 

> @cofyc since this requires a new major version, do we want to release a new minor version first before this PR?

Yes, we can release a minor version first.

**Comment by HaveFun83** [comment]
> Great work! It's a big PR, I need some time to review and test locally.
Thanks @cofyc  if i can assist in any topic. Please let me know

**Comment by HaveFun83** [comment]
@cofyc don't know what happen to the cla check here?
cla and github account looking good.

**Comment by cofyc** [comment]
you need to check emails in your commits.  I suggest you squash them into one or a few logical commits first.  you can refer to this doc: https://github.com/kubernetes/community/blob/master/contributors/guide/github-workflow.md#squash-and-merge

**Pull request closed without merging**
