### PR TITLE
improv: Accept `labelsForPV` elements in the chart

### PR DESCRIPTION
**Pull request by maybe-sybr**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
This change exposes the `labelsForPV` option for the provisioner to users of
the helm chart.

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Release note**:
```

```

### CODE REVIEW

**Comment by cofyc** [comment]
/ok-to-test
I think it's better to update the default values yaml files too. Commented out.
btw, please update the docs here https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/blob/master/helm/README.md#configurations

**Comment by maybe-sybr** [comment]
Should be good now, @cofyc - I can resolve the trivial conflict between this and #219 or you can feel free to do that on my behalf :)

**Comment by maybe-sybr** [comment]
Rebased to fix the conflict - thanks for the merges!

**Comment by cofyc** [comment]
/lgtm
/approve
Thanks for the improvements!

**Comment by maybe-sybr** [comment]
@cofyc Looks like a test failed, maybe a transient failure?

**Comment by maybe-sybr** [comment]
Hmm, that e2e test looks like it's been failing consistently on this PR but I'm not familiar enough with the CI system to know if it's broken or if this changeset has somehow broken it. Any insights, @cofyc ?

**Pull request merged**
