### PR TITLE
Update image registry to gcr

### PR DESCRIPTION
**Pull request by Kartik494**
**What type of PR is this?**

> /kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Release note**:
```
NONE
```

### CODE REVIEW

**Comment by Kartik494** [comment]
In reference to PR https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/pull/241 i have changed the Registry to ` k8s.gcr.io`

**Comment by cofyc** [comment]
/ok-to-test
/lgtm
/approve
Thanks for improvements!

**Comment by Kartik494** [comment]
Hi @cofyc if you could let me know that this [script](https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/blob/master/hack/run-e2e.sh#L84) is also needs to be changes accordingly , as i saw e2e test pull fail due to image not find

**Comment by cofyc** [comment]
> Hi @cofyc if you could let me know that this [script](https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/blob/master/hack/run-e2e.sh#L84) is also needs to be changes accordingly , as i saw e2e test pull fail due to image not find

yes

**Comment by Kartik494** [comment]
Hi , Added a commit for changes in `run-e2e-script.sh`

**Comment by Kartik494** [comment]
Hi @cofyc Could you please take a look, Thanks

**Pull request merged**
