### PR TITLE
fix: init-buildx build failure

### PR DESCRIPTION
**Pull request by andyzhangx**
**What type of PR is this?**
 /kind failing-test

**What this PR does / why we need it**:
fix: init-buildx build failure

Now the pipeline failed with:
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/canary-sig-storage-local-static-provisioner-push-images/1516187005245984768
```
# Ensure we use a builder that can leverage it (the default on linux will not)
DOCKER_CLI_EXPERIMENTAL=enabled docker buildx rm multiarch-multiplatform-builder
error: no builder "multiarch-multiplatform-builder" found
make: [Makefile:96: init-buildx] Error 1 (ignored)
```

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Release note**:
```release-note
none
```

### CODE REVIEW

**Comment by mauriciopoppe** [comment]
the error is already ignored by doing `-$(DOCKER)`, the failure on that job was already fixed in https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/pull/308 but the job runs once a week so it should be ok in the next run

**Comment by andyzhangx** [comment]
thanks for the clarification.

**Comment by andyzhangx** [comment]
well, I think that PR did not fix it:

https://k8s-testgrid.appspot.com/sig-storage-image-build#canary-sig-storage-local-static-provisioner-push-images
```
DOCKER_CLI_EXPERIMENTAL=enabled docker buildx rm multiarch-multiplatform-builder
error: no builder "multiarch-multiplatform-builder" found
make: [Makefile:96: init-buildx] Error 1 (ignored)
```

shall we try this PR?

**Comment by mauriciopoppe** [comment]
I think it's not failing in that line, instead it timed out after 1h30m. It could be because we have a few images for Linux/Windows to build, a similar job that was hand written is passing in around 1h, there's more info about the hand written job here: https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/issues/297#issuecomment-1081254219

**Comment by mauriciopoppe** [comment]
I read the logs and there are some binaries which are taking a really long time to build in CI, e.g.

```
#12 [builder 5/5] RUN GO111MODULE=off CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -a -ldflags '-extldflags "-static"' -o _output/linux/arm64/local-volume-provisioner ./cmd/local-volume-provisioner
#12 DONE 2502.1s
```

That's around ~41 minutes! In comparison, in the job that already succeeded I see:

```
#12 [builder 5/5] RUN GO111MODULE=off CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -a -ldflags '-extldflags "-static"' -o _output/linux/arm64/local-volume-provisioner ./cmd/local-volume-provisioner
#12 DONE 618.0s
```

I think I'll wait for another run, 1h30m is already long enough

**Comment by andyzhangx** [comment]
@mauriciopoppe I think it would be fixed by this PR: https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/pull/313, it could improve image build perf.

**Pull request closed without merging**
