### PR TITLE
Update Klog to V2

### LINKED ISSUE #233: Update Klog to V2
**What happened**:

I have a query regarding dependency update of klog. This repo is using Klog v1 should we update this to use Klog latest version Klog v2 here? Could you let me know is there any dependency conflict while upgrading this to klog v2
 
**What you expected to happen**:

Update the Klog dependency to use V2 instead

**Environment**:
- CSI Driver version:
- Kubernetes version (use `kubectl version`): version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:51:19Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

- OS (e.g. from /etc/os-release): NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"

- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by Kartik494**
**What type of PR is this?**

 /kind bug

**What this PR does / why we need it**:

This PR update Klog to Klog/v2

**Which issue(s) this PR fixes**:

Fixes #233 

**Special notes for your reviewer**:

**Release note**:
```

```

### CODE REVIEW

**Comment by Kartik494** [comment]
Hi @cofyc The test 9/16 is showing failed there inbuild-log.txt
And when i test them in my local environment it is succedeed, Could ypu please give some sights on this. Thanks

`Step 9/16 : RUN GO111MODULE=off CGO_ENABLED=0 GOOS=${OS} GOARCH=${ARCH} go build -a -ldflags '-extldflags "-static"' -o _output/${OS}/${ARCH}/local-volume-provisioner ./cmd/local-volume-provisioner
 ---> Running in 009e26ff1b8d
Removing intermediate container 009e26ff1b8d
 ---> 09a965fe1042
Step 10/16 : FROM k8s.gcr.io/debian-base-${ARCH}:v1.0.0
 ---> 204e96332c91
Step 11/16 : ARG OS=linux
 ---> Using cache
 ---> 1d6fa7510c24`

**Comment by cofyc** [comment]
like kubernetes/kubernetes, we add `vendor/` in git repo, you need to run `hack/update-vendor.sh` to update `vendor/` directory and commit it.

> And when i test them in my local environment it is succeeded, Could you please give some sights on this.

it seems that we need to explicitly disable module mode in Makefile and related scripts, otherwise `vendor/` may be ignored in local development.

**Comment by Kartik494** [comment]
@cofyc Yes i have added vendor dependency in the latest commit but it fails here again. Let me check on this 

> it seems that we need to explicitly disable module mode in Makefile and related scripts, otherwise vendor/ may be ignored in local development.

Thanks

**Comment by Kartik494** [comment]
@cofyc Could You please take a look

**Comment by Kartik494** [comment]
> it seems that we need to explicitly disable module mode in Makefile and related scripts, otherwise vendor/ may be ignored in local development.

Although i have not done any changes regarding this i have just add `vendor/` here i have done it in my previous commit  also but that doesn't work there. Now it is working

**Comment by cofyc** [comment]
/lgtm
/approve
Thanks!

**Pull request merged**
