### PR TITLE
Bump go version to 1.16

### PR DESCRIPTION
**Pull request by Kartik494**

### CODE REVIEW

**Comment by Kartik494** [comment]
Hi @cofyc Could you please take a look

**Comment by cofyc** [comment]
have you tried to run `hack/update-vendor.sh` locally?

**Comment by Kartik494** [comment]
Hi i have run the script  `/hack/update-all.sh` in my local env and got the output as 

/go/src/sigs.k8s.io/sig-storage-local-static-provisioner$ ./hack/update-all.sh 
*** IMPORTANT NOTE ***
This script is used to update generated yaml files from helm values
automatically. It does not validate generated yaml files. Please check to make
sure generated files are what you expected.
*** IMPORTANT NOTE ***
====== HELM v2 ========
Generating with helm v2.16.1 generated_examples/helm2/baremetal-affinity.yaml from examples/baremetal-affinity.yaml
Generating with helm v2.16.1 generated_examples/helm2/baremetal-cleanbyjobs.yaml from examples/baremetal-cleanbyjobs.yaml
Generating with helm v2.16.1 generated_examples/helm2/baremetal-default-storage.yaml from examples/baremetal-default-storage.yaml
Generating with helm v2.16.1 generated_examples/helm2/baremetal-nodeselector.yaml from examples/baremetal-nodeselector.yaml
Generating with helm v2.16.1 generated_examples/helm2/baremetal-priority-critical.yaml from examples/baremetal-priority-critical.yaml
Generating with helm v2.16.1 generated_examples/helm2/baremetal-priority-noncritical.yaml from examples/baremetal-priority-noncritical.yaml
Generating with helm v2.16.1 generated_examples/helm2/baremetal-prometheus.yaml from examples/baremetal-prometheus.yaml
Generating with helm v2.16.1 generated_examples/helm2/baremetal-resyncperiod.yaml from examples/baremetal-resyncperiod.yaml
Generating with helm v2.16.1 generated_examples/helm2/baremetal-tolerations.yaml from examples/baremetal-tolerations.yaml
Generating with helm v2.16.1 generated_examples/helm2/baremetal-without-rbac.yaml from examples/baremetal-without-rbac.yaml
Generating with helm v2.16.1 generated_examples/helm2/baremetal-with-resource-limits.yaml from examples/baremetal-with-resource-limits.yaml
Generating with helm v2.16.1 generated_examples/helm2/baremetal.yaml from examples/baremetal.yaml
Generating with helm v2.16.1 generated_examples/helm2/eks-nvme-ssd.yaml from examples/eks-nvme-ssd.yaml
Generating with helm v2.16.1 generated_examples/helm2/gce-pre1.9.yaml from examples/gce-pre1.9.yaml
Generating with helm v2.16.1 generated_examples/helm2/gce-retain.yaml from examples/gce-retain.yaml
Generating with helm v2.16.1 generated_examples/helm2/gce.yaml from examples/gce.yaml
Generating with helm v2.16.1 generated_examples/helm2/gke.yaml from examples/gke.yaml
====== HELM v3 ========
Generating with helm v3.1.2 generated_examples/baremetal-affinity.yaml from examples/baremetal-affinity.yaml
Generating with helm v3.1.2 generated_examples/baremetal-cleanbyjobs.yaml from examples/baremetal-cleanbyjobs.yaml
Generating with helm v3.1.2 generated_examples/baremetal-default-storage.yaml from examples/baremetal-default-storage.yaml
Generating with helm v3.1.2 generated_examples/baremetal-nodeselector.yaml from examples/baremetal-nodeselector.yaml
Generating with helm v3.1.2 generated_examples/baremetal-priority-critical.yaml from examples/baremetal-priority-critical.yaml
Generating with helm v3.1.2 generated_examples/baremetal-priority-noncritical.yaml from examples/baremetal-priority-noncritical.yaml
Generating with helm v3.1.2 generated_examples/baremetal-prometheus.yaml from examples/baremetal-prometheus.yaml
Generating with helm v3.1.2 generated_examples/baremetal-resyncperiod.yaml from examples/baremetal-resyncperiod.yaml
Generating with helm v3.1.2 generated_examples/baremetal-tolerations.yaml from examples/baremetal-tolerations.yaml
Generating with helm v3.1.2 generated_examples/baremetal-without-rbac.yaml from examples/baremetal-without-rbac.yaml
Generating with helm v3.1.2 generated_examples/baremetal-with-resource-limits.yaml from examples/baremetal-with-resource-limits.yaml
Generating with helm v3.1.2 generated_examples/baremetal.yaml from examples/baremetal.yaml
Generating with helm v3.1.2 generated_examples/eks-nvme-ssd.yaml from examples/eks-nvme-ssd.yaml
Generating with helm v3.1.2 generated_examples/gce-pre1.9.yaml from examples/gce-pre1.9.yaml
Generating with helm v3.1.2 generated_examples/gce-retain.yaml from examples/gce-retain.yaml
Generating with helm v3.1.2 generated_examples/gce.yaml from examples/gce.yaml
Generating with helm v3.1.2 generated_examples/gke.yaml from examples/gke.yaml
Done.

and when i run `hack/update-vendor.sh` the script ran successfully but doesn't update any dependecny in `/vendor/module.txt`

**Comment by Kartik494** [comment]
Closing this PR in reference for #264

**Pull request closed without merging**
