### PR TITLE
Stop publishing images to quay.io

### PR DESCRIPTION
**Pull request by msau42**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>

/kind cleanup

**What this PR does / why we need it**:
It has been 2.5 years since we started publishing images to registry.k8s.io and deprecated quay.io. It is time to fully switch over.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Release note**:
```release-note
Images are no longer published on quay.io. Use registry.k8s.io for image access.
```

### CODE REVIEW

**Comment by msau42** [comment]
/hold

I need to disable and fix the release and test jobs first.

**Comment by msau42** [comment]
/assign @mauriciopoppe 

Release jobs being removed in https://github.com/kubernetes/test-infra/pull/30180

**Review by mauriciopoppe — COMMENTED** [review]
/lgtm

**Comment by msau42** [comment]
Confirmed that latest CI job is using gcr.io/k8s-staging-sig-storage instead of quay:
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-sig-storage-local-static-provisioner-master-gce-latest/1683889834990505984/build-log.txt

/hold cancel

**Pull request merged**
