### PR TITLE
 Add affinty to helm chart

### LINKED ISSUE #203: Helm Chart: Support Affintiy
- Currently helm chart does not support affintity.

- Daemonset in values should support affinity which can be added to the deamonset spec.

### PR DESCRIPTION
**Pull request by AdheipSingh**
`/kind feature`

**Which issue(s) this PR fixes**:

Fixes #203 

- Add support for affinity.
- Added example

### CODE REVIEW

**Comment by AdheipSingh** [comment]
```ok-to-test```

**Comment by cofyc** [comment]
Thanks for your contribution!
/lgtm
/approve

**Pull request merged**
