### PR TITLE
Sync different examples yamls 

### LINKED ISSUE #343: Move examples to have all of them in a single location
**Is your feature request related to a problem?/Why is this needed**

https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/pull/341/files added missing config to an example in `deployment/kubernetes/example`, however there are more examples in `examples/`. I think we should have a single place for examples.

### PR DESCRIPTION
**Pull request by Kartik494**
**What type of PR is this?**
> /kind cleanup

**What this PR does / why we need it**:
This PR sync all the deployment under one directory i.e `/deployment/kubernetes/example`

**Which issue(s) this PR fixes**:

Fixes #343 

**Special notes for your reviewer**:

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by Kartik494** [comment]
@mauriciopoppe PTAL

**Comment by mauriciopoppe** [comment]
/ok-to-test

I saw that `deployment/kubernetes/example` is an example of installing LVP, `examples/` are example of how they're used, with that in mind I think they should be in different places, however, I think these examples can be moved to `deployment/kubernetes`?

Keeping the structure as it is would also work fine

**Comment by Kartik494** [comment]
It's look ok for me as well if we put them together in single place . But  please let me know if you want  the structure as it is before.

**Comment by mauriciopoppe** [comment]
I think the current structure works for me, sorry for any confusion I created in https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/issues/343

**Comment by Kartik494** [comment]
> I think the current structure works for me, sorry for any confusion I created in #343

Sure i will close this PR as per comment that you are ok with the current structure

**Pull request closed without merging**
