### PR TITLE
Make pod security policy in Helm chart valid

### PR DESCRIPTION
**Pull request by weargoggles**
The earlier PR #73 contained an invalid PodSecurityPolicy. Oops.

### CODE REVIEW

**Comment by msau42** [comment]
/assign @cofyc 
are we able to have an e2e test config that uses pod security policy?

**Comment by cofyc** [comment]
> are we able to have an e2e test config that uses pod security policy? 

I've opened an issue to test helm example (https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/issues/64), but this is not easy to test because it requires PodSecurityPolicy admission plugin is in effect.

**Pull request merged**
