### PR TITLE
Release chart as a package and publish it on gh-pages branch

### PR DESCRIPTION
**Pull request by skylenet**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>

 /kind feature

**What this PR does / why we need it**:

Uses chart releaser and chart testing github actions to automatically lint and release the helm chart to the `gh-pages` branch within this repo. 

**Which issue(s) this PR fixes**:

Fixes https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/issues/35

**Special notes for your reviewer**:

Note: Before this gets merged, someone will need to create an empty `gh-pages` branch. That branch is where the helm index.yaml will be published into by the charts releaser. See an example on my fork: https://github.com/skylenet/sig-storage-local-static-provisioner/tree/gh-pages 

**Release note**:
```
- You can now pull the provisioner helm chart via our repository: https://kubernetes-sigs.github.io/helm/sig-storage-local-static-provisioner
```

### CODE REVIEW

**Comment by skylenet** [comment]
CLA signed

**Comment by cofyc** [comment]
`gh-pages` branch is created

**Comment by cofyc** [comment]
@skylenet the `gh-pages` branch is not created empty. I empty and pushed it again. But it seems that I can't to rerun the job to fix it: https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/runs/4331374565
how to release the chart?

**Comment by stevehipwell** [comment]
@cofyc issue #289 has been opened to track the failing publish and I've added what I suspect will be the solution.

**Pull request merged**
