### PR TITLE
fix helm chart annotation

### PR DESCRIPTION
**Pull request by j13tw**
Signed-off-by: ZhengSheng0524 <j13tw@yahoo.com.tw>

**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
/assign @wongma7

**Release note**:
```release-note
just fix helm chart annotation lost char "classe" -> "classes"
```

### CODE REVIEW

**Comment by andyzhangx** [comment]
@j13tw could you sign the cla? thanks.

**Comment by j13tw** [comment]
@andyzhangx I already sign the CLA, thanks!

**Comment by mauriciopoppe** [comment]
This needs to be updated with the latest changes

/remove lgtm

**Pull request closed without merging**
