### PR TITLE
feat(helm): Added support for additional volumes

### PR DESCRIPTION
**Pull request by stevehipwell**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
This PR adds support for providing volumes to init containers and the main container. A specific use case would be adding a script to an init container via a ConfigMap. This is done via the addition of `additionalVolume`s & `additionalVolumeMounts` inputs which allow for the addition of pod volumes and also support mounting extra volumes to the default container (init container volume mounts are part of the `initContainers` value).

It also removes the `additionalHostPathVolumes` value which wasn't ever used to mount a volume to the main container as it was only used in the templates for `volumes` and not `volumeMounts`.

This PR supercedes #386.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Release note**:
```release-note

```

### CODE REVIEW

**Review by mauriciopoppe — COMMENTED** [review]
Looks good, do we need to change the example values and their generated output too? Ref https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/blob/master/hack/verify-generated.sh

**Comment by stevehipwell** [comment]
@mauriciopoppe the removed value wasn't used anywhere so we should be good.

**Review by mauriciopoppe — COMMENTED** [review]
Could you please add an example and its generated output setting both `additionalVolumes` and `additionalVolumeMounts`? Those types of snapshot tests have helped a lot in the past when making refactors.

**Comment by mauriciopoppe** [comment]
It's available now

**Pull request merged**
