### PR TITLE
doc: add code coverage

### PR DESCRIPTION
**Pull request by andyzhangx**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
doc: add code coverage
/assign @cofyc 

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Release note**:
```
none
```

### CODE REVIEW

**Comment by cofyc** [comment]
the license check is failing because we have license issues?

**Comment by andyzhangx** [comment]
> the license check is failing because we have license issues?

not sure, I think you could access the details: https://app.fossa.io/projects/git%2Bgithub.com%2Fkubernetes-sigs%2Fsig-storage-local-static-provisioner/refs/branch/master/f508f11c8c25cdc273ab77a59a1c7e04c52c1063/preview

it said "6 Unlicensed Dependencies"

**Comment by andyzhangx** [comment]
I have removed the license check tag.

**Comment by cofyc** [comment]
ok, we can add the code coverage badge first

/lgtm
/approve

**Pull request merged**
