### PR TITLE
Changelog for 2.6.0

### PR DESCRIPTION
**Pull request by mauriciopoppe**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
/kind documentation

**What this PR does / why we need it**:
CHANGELOG for 2.6.0, generated with the instructions in RELEASE.md from https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/pull/299

**Release note**:
```release-note
NONE
```

/hold
Waiting for other changes to be merged, I'll keep the new file up to date https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/pull/299

### CODE REVIEW

**Comment by andyzhangx** [comment]
@mauriciopoppe shall we publish a release for 2.5.0 now? current latest release is v2.4.0, so it should be v2.5.0 release. Let me know what I could help, thanks.

**Comment by mauriciopoppe** [comment]
yes, I think somewhere in the dev process I made a mistake and pushed the helm chart with v2.5.0, anyways I think we could match the helm version with the repo version and have v2.6.0 for the next release

**Comment by mauriciopoppe** [comment]
I'll create a new one instead.

**Pull request closed without merging**
