### PR TITLE
Upgrade Go version to 1.16

### PR DESCRIPTION
**Pull request by Kartik494**
**Release note**:
```
NONE
```

### CODE REVIEW

**Comment by cofyc** [comment]
run `hack/update-all.sh` and commit again

**Comment by Kartik494** [comment]
Hi @cofyc  the script doesn't run in my enviorment . It throws error as 
`~/go/src/github.com/kubernetes-sigs/sig-storage-local-static-provisioner$ ./hack/update-all.sh 
hack/update-gofmt.sh: line 28: GOPATH: unbound variable`

I wonder here in [script](xargs -n 1 -I pkg gofmt -s -w ${GOPATH}/src/pkg <<<"${PKGS}") from where we get value of `GOPATH` here ? Could you please let me know regarding this

**Comment by cofyc** [comment]
> Hi @cofyc the script doesn't run in my enviorment . It throws error as
> `~/go/src/github.com/kubernetes-sigs/sig-storage-local-static-provisioner$ ./hack/update-all.sh hack/update-gofmt.sh: line 28: GOPATH: unbound variable`
> 
> I wonder here in [script](https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/blob/master/hack/update-gofmt.sh#L28) from where we get value of `GOPATH` here ? Could you please let me know regarding this

can you replace `${GOPATH}` with `$(go env GOPATH)` and run again?

**Comment by Kartik494** [comment]
Hi @cofyc i have tried this in my environment  and i found that the  https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/tree/master/pkg has not been tested . i.e it is unable to locate that file or directory.

**Comment by Kartik494** [comment]
I have run the script from root user and from hack directory as well. When i run the script using `${GOPATH}` then its shows error as unbound GOPATH variable.

**Comment by cofyc** [comment]
It seems like your commits in this branch are gone

**Comment by Kartik494** [comment]
@cofyc  yes, i have run the scripts in my environment that successfully run and make test also passed but when i forced push the commit i get to know that my changes are gone and this PR is closed

**Comment by Kartik494** [comment]
Is there any way to get it open here you could suggest.Thanks

**Comment by cofyc** [comment]
create a new PR instead?

**Comment by Kartik494** [comment]
Sure I will created a new PR.Thanks

**Pull request closed without merging**
