### PR TITLE
handle DeletedFinalStateUnknown object when receiving PV delete event

### PR DESCRIPTION
**Pull request by loveRhythm1990**
**What type of PR is this?**
 /kind bug

**What this PR does / why we need it**:
 Watch connection closed periodically, when Watch restart and do a relist, PV deletion event may lost, this leads to local cache contains a stale PV, which cannot be deleted, also new PV will not created. 

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:
I will paste related logs

**Release note**:
```

```

### CODE REVIEW

**Comment by loveRhythm1990** [comment]
I0906 17:06:26.812629       1 cache.go:64] Updated pv "local-pv-fb8c73a" to cache
I0906 17:06:26.812633       1 cache.go:64] Updated pv "local-pv-ddfb799d" to cache
I0906 17:08:14.980251       1 cache.go:64] Updated pv "local-pv-8d45386f" to cache
I0906 17:08:24.408193       1 deleter.go:195] Start cleanup for pv local-pv-8d45386f
I0906 17:08:24.408243       1 deleter.go:266] Deleting PV file volume "local-pv-8d45386f" contents at hostpath "/disks/local-ssd/pv0", mountpath "/disks/local-ssd/pv0"
W0906 17:08:43.816709       1 reflector.go:270] k8s.io/client-go/informers/factory.go:132: watch of *v1.PersistentVolume ended with: too old resource version: 303648857 (303651327)
I0906 17:08:44.409001       1 deleter.go:165] Deleting pv local-pv-8d45386f after successful cleanup
I0906 17:08:44.823951       1 cache.go:64] Updated pv "local-pv-785a9d74" to cache
I0906 17:08:44.823975       1 cache.go:64] Updated pv "local-pv-fb8c73a" to cache
I0906 17:08:44.823997       1 cache.go:64] Updated pv "local-pv-ddfb799d" to cache
E0906 17:08:44.824013       1 populator.go:87] Added object is not a v1.PersistentVolume type
I0906 17:08:54.413050       1 deleter.go:195] Start cleanup for pv local-pv-8d45386f
I0906 17:08:54.413100       1 deleter.go:266] Deleting PV file volume "local-pv-8d45386f" contents at hostpath "/disks/local-ssd/pv0", mountpath "/disks/local-ssd/pv0"
I0906 17:09:04.413461       1 deleter.go:165] Deleting pv local-pv-8d45386f after successful cleanup
I0906 17:09:14.416189       1 deleter.go:195] Start cleanup for pv local-pv-8d45386f
I0906 17:09:14.416293       1 deleter.go:266] Deleting PV file volume "local-pv-8d45386f" contents at hostpath "/disks/local-ssd/pv0", mountpath "/disks/local-ssd/pv0"

**Comment by loveRhythm1990** [comment]
Notice following logs:
`E0906 17:08:44.824013 1 populator.go:87] Added object is not a v1.PersistentVolume type`
actually, It is handling deletion event, (we need change "Added" to "Deleted", which is a log mistake)，It is a DeletedFinalStateUnknown object

**Comment by loveRhythm1990** [comment]
@jsafrane @saad-ali

**Comment by cofyc** [comment]
/lgtm
Thanks for the fix!

**Pull request merged**
