### PR TITLE
Fix #203: Add affinty to helm chart

### LINKED ISSUE #203: Helm Chart: Support Affintiy
- Currently helm chart does not support affintity.

- Daemonset in values should support affinity which can be added to the deamonset spec.

### PR DESCRIPTION
**Pull request by AdheipSingh**
`/kind feature`

**Which issue(s) this PR fixes**:

Fixes #203 

- Add support for affinity.
- Added example

### CODE REVIEW

**Comment by cofyc** [comment]
/ok-to-test
Thanks! Can you document it here: https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/tree/master/helm#configurations?

**Comment by AdheipSingh** [comment]
@cofyc 
Am i missing something in this PR, not sure why the CI is failing. Do i need to add the example in helm 2 ?

**Comment by cofyc** [comment]
```
==== HELM v2====
Checking examples/baremetal-affinity.yaml failed, diff: 
diff: generated_examples/helm2/baremetal-affinity.yaml: No such file or directory
make: *** [Makefile:50: verify] Error 1
```

yes, try `hack/update-generated.sh` and check the auto-generated file

**Comment by cofyc** [comment]
> [Keywords](https://help.github.com/articles/closing-issues-using-keywords) which can automatically close issues and at(@) mentions are not allowed in commit messages.
> 
> **The list of commits with invalid commit messages**:
> 
> * [7be8e46](https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/commits/7be8e4608e7b4cf6e6de6b59a180279ad7d38fc8) Fix #203: Add affinty to helm chart
> * [f468a43](https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/commits/f468a43e27ec064c004f66fafa94cbb9f3ebcbbc) Fix #203: Add doc for affinity
> * [7cbe8e6](https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/commits/7cbe8e6b7920ce8ca162d71cba33ce2662660fc6) FIX #230: add generated file

@AdheipSingh can you fix the commit message and squash the commits?

**Comment by AdheipSingh** [comment]
Closing this, will re-open in separate branch

**Pull request closed without merging**
