### PR TITLE
DOCS: correct typo in header level

### PR DESCRIPTION
**Pull request by ebCrypto**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind test
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Release note**:
```release-note

```

### CODE REVIEW

**Comment by andyzhangx** [comment]
@ebCrypto could you sign the cla first? thanks.

**Comment by ebCrypto** [comment]
> @ebCrypto could you sign the cla first? thanks.

@andyzhangx Apologies, signing a docusign is too much bureaucracy: all I was trying to do is help out by fixing a typo. Feel free to close the PR.

**Comment by andyzhangx** [comment]
@ebCrypto could you sign the cla first? thanks.

**Comment by andyzhangx** [comment]
@ebCrypto can you sign up the cla first? thanks.

**Pull request closed without merging**
