### PR TITLE
Add LKE Option to Bring up Local Disks

### PR DESCRIPTION
**Pull request by rsyracuse**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
This PR Includes information on using LKE for sig-storage-local-static-provisioner

**Which issue(s) this PR fixes**:
N/A

**Special notes for your reviewer**:

**Release note**:

### CODE REVIEW

**Comment by rsyracuse** [comment]
CLA was signed, feel free to reach out if you need anything else!

**Comment by cofyc** [comment]
> CLA was signed, feel free to reach out if you need anything else!

the `cla/linuxfoundation` check does not pass, did you sign the CLA with the email in your commit?

**Comment by rsyracuse** [comment]
> > CLA was signed, feel free to reach out if you need anything else!
> 
> the `cla/linuxfoundation` check does not pass, did you sign the CLA with the email in your commit?

Apologies, looks like I missed a step. Should be ok now

**Comment by cofyc** [comment]
/approve
/lgtm
Thanks!

**Pull request merged**
