### PR TITLE
improv: Add opt-out for `/dev` volume in the chart

### PR DESCRIPTION
**Pull request by maybe-sybr**
*What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
For filesystem only based provisioning, `/dev/` shouldn't need to be
mounted so we add a new value to opt-out of defining it in the chart.

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Release note**:
```

```

### CODE REVIEW

**Comment by maybe-sybr** [comment]
The CLA should be fine now - it went green in my other PR

**Comment by cofyc** [comment]
/ok-to-test
Thanks!
btw, can you update the docs here? https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/tree/master/helm#configurations

**Comment by maybe-sybr** [comment]
Should be good now, @cofyc - thanks for the quick review :)

**Pull request merged**
