### PR TITLE
test: add travis CI to get code coverage data

### PR DESCRIPTION
**Pull request by andyzhangx**
**What type of PR is this?**
/kind test

**What this PR does / why we need it**:
test: add travis CI to enable code coverage data
copy from:  https://github.com/kubernetes-sigs/azurefile-csi-driver

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Release note**:
```
none
```

### CODE REVIEW

**Comment by cofyc** [comment]
how about using [Github Actions](https://help.github.com/en/actions)? I'm not sure if I can enable travis CI on this repo. Github Actions is simple to use too.

**Comment by andyzhangx** [comment]
> how about using [Github Actions](https://help.github.com/en/actions)? I'm not sure if I can enable travis CI on this repo. Github Actions is simple to use too.

not sure, can you enable this: https://travis-ci.org/organizations/kubernetes-sigs/repositories, with test coverage data, we could let some interns to improve unit test coverage.

**Comment by andyzhangx** [comment]
do you have the permission?
image

**Comment by cofyc** [comment]
can you convert Travis configuration to Github Actions? then we don't need to depend on third party service.

**Comment by cofyc** [comment]
found coveralls has a [github actions module](https://github.com/marketplace/actions/coveralls-github-action) we can use

**Comment by andyzhangx** [comment]
> found coveralls has a [github actions module](https://github.com/marketplace/actions/coveralls-github-action) we can use

could you @animeshk08 take a look? we have same requirement on SMB csi driver since I don't have the permission to enable on kubernetes-csi project, thanks.

**Comment by cofyc** [comment]
forget my previous suggestion, https://github.com/marketplace/actions/coveralls-github-action is not suitable for go project.

nevertheless, https://github.com/mattn/goveralls supports github actions too.

**Comment by andyzhangx** [comment]
> forget my previous suggestion, https://github.com/marketplace/actions/coveralls-github-action is not suitable for go project.
> 
> nevertheless, https://github.com/mattn/goveralls supports github actions too.

so shall we go with this PR? If you have the permission to enable it, it's quite easy to get code coverage data.

**Comment by cofyc** [comment]
can you update this PR to use Github Action? I've tested `https://github.com/mattn/goveralls` on my personal fork with Github Actions, see https://github.com/cofyc/sig-storage-local-static-provisioner/blob/master/.github/workflows/go.yml.

You can copy this file to `.github/workflows/go.yml`.

It's great to have test coverage data. My suggestion is to use Github service then we don't need to install Travis CI for this repo.

**Comment by andyzhangx** [comment]
> can you update this PR to use Github Action? I've tested `https://github.com/mattn/goveralls` on my personal fork with Github Actions, see https://github.com/cofyc/sig-storage-local-static-provisioner/blob/master/.github/workflows/go.yml ([an example run](https://github.com/cofyc/sig-storage-local-static-provisioner/actions/runs/112052588))
> 
> You can copy this file to `.github/workflows/go.yml`.
> 
> It's great to have test coverage data. My suggestion is to use Github service then we don't need to install Travis CI for this repo.

done, so where is the test coverage data after this PR merged?

**Comment by cofyc** [comment]
> > can you update this PR to use Github Action? I've tested `https://github.com/mattn/goveralls` on my personal fork with Github Actions, see https://github.com/cofyc/sig-storage-local-static-provisioner/blob/master/.github/workflows/go.yml ([an example run](https://github.com/cofyc/sig-storage-local-static-provisioner/actions/runs/112052588))
> > You can copy this file to `.github/workflows/go.yml`.
> > It's great to have test coverage data. My suggestion is to use Github service then we don't need to install Travis CI for this repo.
> 
> done, so where is the test coverage data after this PR merged?

it should be on this page: https://coveralls.io/github/kubernetes-sigs/sig-storage-local-static-provisioner?branch=master

**Comment by andyzhangx** [comment]
> > > can you update this PR to use Github Action? I've tested `https://github.com/mattn/goveralls` on my personal fork with Github Actions, see https://github.com/cofyc/sig-storage-local-static-provisioner/blob/master/.github/workflows/go.yml ([an example run](https://github.com/cofyc/sig-storage-local-static-provisioner/actions/runs/112052588))
> > > You can copy this file to `.github/workflows/go.yml`.
> > > It's great to have test coverage data. My suggestion is to use Github service then we don't need to install Travis CI for this repo.
> > 
> > 
> > done, so where is the test coverage data after this PR merged?
> 
> it should be on this page: https://coveralls.io/github/kubernetes-sigs/sig-storage-local-static-provisioner?branch=master

it still needs travis: https://coveralls.io/github/kubernetes-sigs/sig-storage-local-static-provisioner, it's bound to travis ...

**Comment by cofyc** [comment]
the test coverage result is collected now, check https://coveralls.io/github/kubernetes-sigs/sig-storage-local-static-provisioner.

**Comment by cofyc** [comment]
I think we can show the badge in README.md like `azurefile-csi-driver` now ;-)

**Comment by andyzhangx** [comment]
> I think we can show the badge in README.md like `azurefile-csi-driver` now ;-)

sure, will send out another PR.

**Pull request merged**
